// Golden-vector tests against the sample mainnet addresses recorded in
// PARAMETERS.md section 3.1 (generated and verified during Phase 1).
// These addresses were not generated by this Dart code -- they came from
// the C++ node's own address encoding -- so decoding one, then
// re-encoding the extracted hash, is a real cross-implementation
// round-trip check, not just internal self-consistency.
import 'dart:typed_data';

import 'package:cac_wallet/config/network_config.dart';
import 'package:cac_wallet/crypto/address.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('P2PKH', () {
    const samples = [
      'CRD6aiuoa3sv2ToqcszF3GmjRW8FDdBcHU',
      'CbqE2d8JtcTHwydNmiRVTSasD4oovSF7us',
    ];

    for (final sample in samples) {
      test('decode/re-encode round-trips for $sample', () {
        final decoded = decodeAddress(sample, NetworkConfig.mainnet);
        expect(decoded.type, AddressType.p2pkh);
        expect(decoded.hash.length, 20);
        expect(p2pkhAddress(decoded.hash, NetworkConfig.mainnet), sample);
      });
    }

    test('starts with C on mainnet', () {
      for (final sample in samples) {
        expect(sample.startsWith('C'), isTrue);
      }
    });
  });

  group('P2SH', () {
    const samples = [
      'SipNMPMFEjmmfNnBg92m5h8iS4wvqgihd9',
      'Sd5nU5NcZf2LRx3QGQU872ufmiH5rjhHKS',
    ];

    for (final sample in samples) {
      test('decode/re-encode round-trips for $sample', () {
        final decoded = decodeAddress(sample, NetworkConfig.mainnet);
        expect(decoded.type, AddressType.p2sh);
        expect(decoded.hash.length, 20);
        expect(p2shAddress(decoded.hash, NetworkConfig.mainnet), sample);
      });
    }

    test('starts with S on mainnet', () {
      for (final sample in samples) {
        expect(sample.startsWith('S'), isTrue);
      }
    });
  });

  group('bech32 P2WPKH', () {
    test('round-trips through encode/decode', () {
      final hashBytes = Uint8List.fromList(List<int>.generate(20, (i) => i));
      final address = p2wpkhAddress(hashBytes, NetworkConfig.mainnet);
      expect(address.startsWith('cac1'), isTrue);
      final decoded = decodeAddress(address, NetworkConfig.mainnet);
      expect(decoded.type, AddressType.p2wpkh);
      expect(decoded.hash, hashBytes);
    });
  });

  group('cross-network rejection', () {
    test('mainnet address is rejected on testnet decode', () {
      expect(
        () => decodeAddress('CRD6aiuoa3sv2ToqcszF3GmjRW8FDdBcHU', NetworkConfig.testnet),
        throwsFormatException,
      );
    });
  });
}
